name: Corgea Scan

on: 
  pull_request:
    types:
      - opened

jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - uses: corgea/action@v1
        with:
          corgea-token: ${{ secrets.CORGEA_TOKEN }}
